### ISSUE TITLE
Load a google proto file with imports

### ISSUE THREAD

**Issue by MexXxo** [googleapis/nodejs-proto-files#297]
Hi,

I have an Issue that seems to be in Node 12 & 14.
I'm trying to load the proto of the embeddedAssistant and the imports are loaded with a wrong path.

My test code, that I used on RunKit:
`
const googleProtoFiles = require("google-proto-files");
const protobufjs = require("protobufjs");

const eaPath = googleProtoFiles.embeddedAssistant.v1alpha2;
googleProtoFiles.load(eaPath).then( PD => {
console.log(PD)
});
`

Error: 
"(node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: …assistant/embedded/v1alpha2/google/api/annotations.proto'"

On my own code I get the same issue.

So the import statements is getting looked up with "assistant/embedded/v1alpha2/" as root instead of the google-proto-files part.

Is there any option to set this? I also looked into the protobufjs but could not find anything helpful.

**Comment by MexXxo** [comment]
Maybe as a more direct question. How can I load a proto file that is part of this module?

I thought this should work:
```javascript
const googleProtoFiles = require("google-proto-files");
const protobufjs = require("protobufjs"); // Only needed by RunKit

googleProtoFiles.load( googleProtoFiles.embeddedAssistant.v1alpha2 ).then( PackageDefinition => {
console.log(PD)
});
```

**Comment by MexXxo** [comment]
After some debugging, I could find out that because of some reason the imports are not getting correctly resolved of the protos, so the embedded assistant (also valid for others!) requires the LatLng, however if I add the type directly everything works with these modules:
```javascript
const grpc = require('grpc');
const protoLoader = require('@grpc/proto-loader');
const protoFiles = require('google-proto-files'); 
const packageDefinition = protoLoader.loadSync( path.relative(process.cwd(), protoFiles.embeddedAssistant.v1alpha2) );

const packageObject = grpc.loadPackageDefinition(packageDefinition);
const embedded_assistant_pb = packageObject.google.assistant.embedded.v1alpha2;
const latlngPb = packageObject.LatLng;
```


Otherwise I get this Error:
no such Type or Enum 'google.type.LatLng' in Type .google.assistant.embedded.v1alpha2.DeviceLocation
    at Type.lookupTypeOrEnum (/.../node_modules/@grpc/proto-loader/node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (/.../node_modules/@grpc/proto-loader/node_modules/protobufjs/src/field.js:265:94)
    at Type.resolveAll (/.../node_modules/@grpc/proto-loader/node_modules/protobufjs/src/type.js:304:21)
    at Namespace.resolveAll (/.../node_modules/@grpc/proto-loader/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/.../node_modules/@grpc/proto-loader/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/.../node_modules/@grpc/proto-loader/node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (/.../node_modules/@grpc/proto-loader/node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (/...node_modules/@grpc/proto-loader/node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (/.../node_modules/@grpc/proto-loader/node_modules/protobufjs/src/root.js:248:43)
    at Object.loadSync (/.../node_modules/@grpc/proto-loader/build/src/index.js:218:16)

**Comment by hkdevandla** [comment]
@alexander-fenster , can you please take a look? Thanks!

**Comment by alexander-fenster** [comment]
We added `LatLng` not too long ago and this package just needs to be updated to include it. I will do it.

**Comment by MexXxo** [comment]
Thanks for the bugfix! 👍
